title: lloliloll
author: author unknown
email: your-email@domain.com
description: lloliloll and github story # this means to ignore newlines until "baseurl:"
# social links
twitter_username: random # DO NOT include the @ character, or else the build will fail!
github_username: llolilol # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
