title: fragments of freedom
author: ">cheeba"
email: your-email@domain.com
description: # this means to ignore newlines until "baseurl:"
selfdescriptionless
# social links
twitter_username: testapod # DO NOT include the @ character, or else the build will fail!
github_username:  ohno # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
