title: title as it is in _config.yml
author: author unknown
email: email@domain.com
description: lloliloll and github story to be indexed by google # this means to ignore newlines until "baseurl:"
# social links
twitter_username: random # DO NOT include the @ character, or else the build will fail!
github_username: llolilol # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
